# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

alias ssloff="git config --global http.sslVerify false"
alias sslon="git config --global http.sslVerify true"

alias 2.="cd ../../"
alias 3.="cd ../../../"
alias 4.="cd ../../../../"
alias 5.="cd ../../../../../"

alias ffiles="find . -type f | grep -v '.git/'"
alias dirgrep="ffiles | xargs grep "

alias lah="ls -lah"

alias tree="cmd //c tree"

alias dotfiles='git --git-dir ~/.dotfiles/.git --work-tree=$HOME'
